World wide web

diff --git a/0x10-https_ssl/0-world_wide_web b/0x10-https_ssl/0-world_wide_web
--- a/0x10-https_ssl/0-world_wide_web
+++ b/0x10-https_ssl/0-world_wide_web
@@ -1,19 +1,35 @@
 #!/usr/bin/env bash
-# Script that will display information about subdomains
+# Script that displays information about subdomains
 
-domain_information() {
-    local domain="$1"
-    local subdomain="$2"
-    local line
-    line=$(dig "$subdomain"."$domain" | awk '/ANSWER SECTION:/ {getline; print; getline; print}')
-    echo "$subdomain $line" | awk '{printf "The subdomain %s is a %s record and points to %s\n", $1, $2, $3}'
+#!/bin/bash
+
+# Bash function to query and display subdomain information
+query_subdomain() {
+    local domain=$1
+    local subdomain=$2
+    local output=$(dig "$subdomain.$domain" | awk '/IN/{print $4, $5}')
+    local record_type=$(echo "$output" | awk '{print $1}')
+    local destination=$(echo "$output" | awk '{print $2}')
+
+    echo "The subdomain $subdomain is a $record_type record and points to $destination"
 }
 
-if [ "$#" -eq 1 ]; then
-    domain_information "$1" "www"
-    domain_information "$1" "lb-01"
-    domain_information "$1" "web-01"
-    domain_information "$1" "web-02"
-elif [ "$#" -eq 2 ]; then
-    domain_information "$1" "$2"
+# Main script logic
+domain=$1
+subdomain=$2
+
+if [ -z "$domain" ]; then
+    echo "Error: Domain name is mandatory."
+    exit 1
 fi
+
+if [ -z "$subdomain" ]; then
+    # Query and display information for the default subdomains
+    for subdomain in www lb-01 web-01 web-02; do
+        query_subdomain "$domain" "$subdomain"
+    done
+else
+    # Query and display information for the specified subdomain
+    query_subdomain "$domain" "$subdomain"
+fi
+
